global using Basket.API.Models;
global using Shared.CQRS;
global using Carter;
global using MediatR;
global using FluentValidation;
global using Shared.Behaviors;
global using Shared.Exceptions;
global using Basket.API.Exceptions;
global using Marten;
